version: 2.0

shared: &shared
  working_directory: ~/django-sb-admin-2-auth
  steps:
    - checkout
    - run: echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
    - run: pip install --user tox
    - run:
        name: Run tests
        command: tox

jobs:
  "pre-commit":
    <<: *shared
    docker:
      - image: circleci/python
    environment:
      TOXENV: pre-commit

workflows:
  version: 2
  build:
    jobs:
      - "pre-commit"
